{
 "title": "Liberty bikes stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Logins",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "totalPlayerNumberGauge" }
   ]
  },
  {
   "title": "Current number of players",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "playerNumberGauge" }
   ]
  },
  {
   "title": "Player actions/sec (last 1 min)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "application_rate_of_websocket_calls_one_min_rate_per_second"
    }
   ]
  },
  {
   "title": "Players in queue",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "currentPartiesCounter" }
   ]
  },
  {
   "title": "Games played",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    { "expr": "currentRoundNumberCounter" }
   ]
  },
  {
   "title": "CPU load (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cpu_systemLoadAverage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Service Health",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 6 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "memory_usedHeap_bytes", "legendFormat": "{{job}}" }
   ]
  }
 ]
}