version: '3'
services:
# TOOD: comment out frontend from docker build for now, because it takes a long time to 
# rebuild the docker image, since we pack a bunch of NPM dependencies in this layer
#  frontend:
#    build: frontend
#    image: libertybikes-frontend
#    ports:
#      - "12000:12000"
  auth:
    build: auth-service
    image: libertybikes-auth
    ports:
      - "8082:8082"
    environment:
      - frontend_url=http://frontend:12000/login
      - auth_url=https://auth:8482/auth-service
  game:
    build: game-service
    image: libertybikes-game
    ports:
      - "8080:8080"
    environment:
      - org_libertybikes_restclient_PlayerService_mp_rest_url=http://player:8081
      - singleParty
  player:
    build: player-service
    image: libertybikes-player
    ports:
      - "8081:8081"
