version: '2.1'
services:
  frontend:
    build: frontend
    image: libertybikes-frontend
    ports:
      - "12000:12000"
  player:
    build: player-service
    image: libertybikes-player
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
  game:
    build: game-service
    image: libertybikes-game
    ports:
     - "8080:8080"
    environment:
      - org_libertybikes_restclient_PlayerService_mp_rest_url=http://player:8081
      - singleParty
